apiVersion: batch/v1
kind: CronJob
metadata:
  name: laravel-schedule
  namespace: laravel-prod
  labels:
    app.kubernetes.io/name: laravel-app
    app.kubernetes.io/component: schedule  # 标识为调度组件
    environment: prod
spec:
  schedule: "*/1 * * * *"  # 每分钟执行一次（Cron 表达式正确）
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: acr-secret  # 镜像拉取密钥（需提前创建）
          containers:
            - name: laravel-schedule
              image: registry.cn-hangzhou.aliyuncs.com/xuancheng/laravel-app
              command: ["php", "artisan", "schedule:run"]  # Laravel 定时任务命令
              envFrom:
                - configMapRef:
                    name: laravel-env-prod  # 引用环境变量 ConfigMap（需提前创建）
                - secretRef:
                    name: laravel-secret-prod    # 敏感变量从 Secret 注入
          restartPolicy: Never  # 任务完成后不重启容器
      backoffLimit: 4  # 失败重试次数（可选，默认 6 次）
  # 可选：如需设置时区（如北京时间），添加以下配置
  # concurrencyPolicy: Forbid  # 禁止并发执行（根据需求选择 Allow/Forbid/Replace）
  # timezone: Asia/Shanghai      # 时区设置（需集群支持）