apiVersion: batch/v1
kind: Job
metadata:
  name: laravel-schedule
  namespace: laravel-prod
  labels:
    app.kubernetes.io/name: laravel-app
    environment: prod
spec:
  template:
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: laravel-schedule
        image: registry.cn-hangzhou.aliyuncs.com/xuancheng/laravel-app
        command: ["php", "artisan", "schedule:run"]
        envFrom:
        - configMapRef:
            name: laravel-env-prod
        - secretRef:
            name: laravel-secret-prod
      restartPolicy: Never
  backoffLimit: 4