apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret-prod
  namespace: laravel-prod
  labels:
    app.kubernetes.io/name: laravel-app
    environment: prod
type: Opaque
data: 
  # 使用以下命令生成真实数据（生产环境）：
  # kubectl create secret generic laravel-secret-prod \
  #   --from-literal=DB_PASSWORD=your_password \
  #   --namespace=laravel-prod \
  #   --dry-run=client -o yaml > manifests/env/prod/secret-env.yaml
  DB_HOST: "实际base64值"       # 示例：echo -n "db.prod.com" | base64
  DB_USERNAME: "实际base64值"   # 示例：echo -n "laravel_prod" | base64
  DB_PASSWORD: "实际base64值"
  REDIS_HOST: "实际base64值"
  REDIS_PASSWORD: "实际base64值"
  APP_KEY: "实际base64值"