apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 基础资源列表
resources:
# - secret-acr.yaml
# - service.yaml
- middleware.yaml

# 通用标签（自动应用于所有资源）
commonLabels:
  app.kubernetes.io/name: laravel-app
  app.kubernetes.io/part-of: argocd-project
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: "2.0.0"