apiVersion: v1
kind: Secret
metadata:
  name: secret-acr
  namespace: laravel
  labels:
    app.kubernetes.io/name: laravel-app
    app.kubernetes.io/role: secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <替换为实际Base64编码的Docker配置>
