apiVersion: v1
kind: Service
metadata:
  name: laravel-app
  labels:
    app.kubernetes.io/name: laravel-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: laravel-app