apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret-staging
  namespace: laravel-staging
  labels:
    app.kubernetes.io/name: laravel-app
    environment: staging
type: Opaque
data: 
  # 使用以下命令生成真实数据（生产环境）：
  # kubectl create secret generic laravel-secret-staging \
  #   --from-literal=DB_PASSWORD=your_password \
  #   --namespace=laravel-staging \
  #   --dry-run=client -o yaml > manifests/env/staging/secret-env.yaml
  DB_HOST: "实际base64值"       # 示例：echo -n "db.staging.com" | base64
  DB_USERNAME: "实际base64值"   # 示例：echo -n "laravel_staging" | base64
  DB_PASSWORD: "实际base64值"
  REDIS_HOST: "实际base64值"
  REDIS_PASSWORD: "实际base64值"
  APP_KEY: "实际base64值"