apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: laravel
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <替换为实际Base64编码的Docker配置>


# 生成说明：
# 1. 执行以下命令生成真实的 .dockerconfigjson 编码值（替换 <> 内的参数）：
#    kubectl create secret docker-registry acr-secret \
#      --docker-server=https://registry.cn-hangzhou.aliyuncs.com \
#      --docker-username=1768177868@qq.com \
#      --docker-password=<你的ACR密码> \
#      -n laravel \
#      --dry-run=client -o yaml | grep '.dockerconfigjson' | awk '{print $2}'
# 2. 将命令输出的字符串替换到 .dockerconfigjson 字段