apiVersion: v1
kind: Secret
metadata:
  name: laravel-app-key
  namespace: laravel  # 替换为实际命名空间
  labels:
    app: laravel
    component: secret
type: Opaque
data:
  APP_KEY: # 此处填写base64编码后的实际密钥  php artisan key:generate

