apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-env
  namespace: laravel
  labels:
    app: laravel
    type: config
data:
  # Laravel 基础配置（非敏感信息）
  APP_ENV: production
  APP_DEBUG: "false"  # 生产环境关闭调试模式
  APP_URL: http://laravel-app.laravel.svc.cluster.local

  # 数据库连接配置（非敏感部分，如主机、端口、数据库名）
  DB_CONNECTION: mysql
  DB_HOST: db-service.laravel
  DB_PORT: "3306"
  DB_DATABASE: laravel  # 建议使用明确的数据库名
  DB_USERNAME: laravel
  DB_PASSWORD: laravel123

  # 队列与缓存配置
  QUEUE_CONNECTION: redis
  REDIS_HOST: redis-service.laravel
  REDIS_PORT: "6379"
  REDIS_PASSWORD: laravel