apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  namespace: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      initContainers:
      - name: migrate-db
        image: registry.cn-hangzhou.aliyuncs.com/xuancheng/laravel-app:1.0.25
        command:
          - sh
          - -c
          - |
            php artisan cache:clear
            php artisan config:clear
            php artisan migrate --force || exit 0
        envFrom:
        - configMapRef:
            name: laravel-env
        - secretRef:
            name: laravel-app-key
        volumeMounts:
        - name: storage-framework-cache
          mountPath: /var/www/html/storage/framework/cache
        - name: storage-framework-views
          mountPath: /var/www/html/storage/framework/views
        - name: storage-app-private
          mountPath: /var/www/html/storage/app/private
        - name: storage-app-public
          mountPath: /var/www/html/storage/app/public
        - name: storage-logs
          mountPath: /var/www/html/storage/logs

      - name: seed-db
        image: registry.cn-hangzhou.aliyuncs.com/xuancheng/laravel-app:1.0.25
        command:
          - sh
          - -c
          - |
            php artisan db:seed --force || exit 0
        envFrom:
        - configMapRef:
            name: laravel-env
        - secretRef:
            name: laravel-app-key
        volumeMounts:
        - name: storage-framework-cache
          mountPath: /var/www/html/storage/framework/cache
        - name: storage-framework-views
          mountPath: /var/www/html/storage/framework/views
        - name: storage-app-private
          mountPath: /var/www/html/storage/app/private
        - name: storage-app-public
          mountPath: /var/www/html/storage/app/public
        - name: storage-logs
          mountPath: /var/www/html/storage/logs

      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: laravel
        image: registry.cn-hangzhou.aliyuncs.com/xuancheng/laravel-app:1.0.25
        ports:
        - containerPort: 80
          name: nginx-http
        envFrom:
        - configMapRef:
            name: laravel-env
        - secretRef:
            name: laravel-app-key
        volumeMounts:
        - name: storage-framework-cache
          mountPath: /var/www/html/storage/framework/cache
        - name: storage-framework-views
          mountPath: /var/www/html/storage/framework/views
        - name: storage-app-private
          mountPath: /var/www/html/storage/app/private
        - name: storage-app-public
          mountPath: /var/www/html/storage/app/public
        - name: storage-logs
          mountPath: /var/www/html/storage/logs

      volumes:
      - name: storage-framework-cache
        emptyDir: {}
      - name: storage-framework-views
        emptyDir: {}
      - name: storage-app-private
        emptyDir: {}
      - name: storage-app-public
        emptyDir: {}
      - name: storage-logs
        emptyDir: {}