apiVersion: batch/v1
kind: Job
metadata:
  name: laravel-schedule
  namespace: laravel
spec:
  template:
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: laravel-schedule
        image: registry.cn-hangzhou.aliyuncs.com/xuancheng/laravel-app:1.0.25
        command: ["php", "artisan", "schedule:run"]
        envFrom:
        - configMapRef:
            name: laravel-env
      restartPolicy: Never
  backoffLimit: 4
