apiVersion: batch/v1
kind: Job
metadata:
  name: laravel-migration
  namespace: laravel
spec:
  template:
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: migration
        image: registry.cn-hangzhou.aliyuncs.com/xuancheng/laravel-app:1.0.25
        command:
        - "/bin/sh"
        - "-c"
        - |
          php artisan migrate --force
          php artisan db:seed --force
        envFrom:
        - configMapRef:
            name: laravel-env
      restartPolicy: Never
  backoffLimit: 4
